apiVersion: v1
kind: Service
metadata:
  labels:
    app: pmm-server
  name: pmm-server
spec:
  type: NodePort
  externalIPs: 
  - 10.0.2.15
  ports:
  - port: 443
    name: https
    targetPort: 443
  - port: 80
    name: http
    targetPort: 80
  selector:
    app: pmm-server